### ISSUE TITLE
startup error Cannot subclass final class cn.beecp.BeeDataSource

### ISSUE THREAD

**Issue by huwsun** [Chris2018998/BeeCP-Starter#6]
spring boot 2.3.3
startup error:
`
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class cn.beecp.BeeDataSource: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class cn.beecp.BeeDataSource
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:208) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:155) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.github.gavlyukovskiy.boot.jdbc.decorator.DataSourceDecoratorBeanPostProcessor.postProcessAfterInitialization(DataSourceDecoratorBeanPostProcessor.java:84) ~[datasource-decorator-spring-boot-autoconfigure-1.6.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 152 common frames omitted
`
`     
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class cn.beecp.BeeDataSource
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:660) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cglib.core.ClassLoaderAwareGeneratorStrategy.generate(ClassLoaderAwareGeneratorStrategy.java:39) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
`

**Comment by Chris2018998** [comment]
这个问题应该是我考虑不周导致的，对不起,。

形成原因: Springboot2.3.3这个版本应该是扩展DataSource类做AOP子类,而 BeeDataSource 是final的类型，导致扩展失败。

我能否先给您一个临时包（用于替换您本地beecp_x.jar包），地址：https://github.com/Chris2018998/BeeCP/blob/master/doc/temp/beecp-2.5.4.2.jar

希望尽快收到您进一步的反馈。

**Comment by huwsun** [comment]
非常感谢，新的包可以了

**Comment by Chris2018998** [comment]
非常感谢您的反馈!
